services:
  erddap:
    image: vliz/custom-erddap:latest
    volumes:

      - "./data/conf/config.sh:/usr/local/tomcat/bin/config.sh"
      - "./data/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt"
      - "./data/data:/erddapData"
      - "./data/datasets:/datasets"

      - "../content:/usr/local/tomcat/content"

      - "../WEB-INF/classes:/usr/local/tomcat/webapps/erddap/WEB-INF/classes"
      - "/tmp/:/usr/local/tomcat/temp/"
    ports:
      - 9001:8080
    environment:
      ERDDAP_MIN_MEMORY: '1G'
      ERDDAP_MAX_MEMORY: '2G'
